# This is a basic workflow to help you get started with Actions

name: deploy-main

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    paths:
      - 'packages/container/**'

defaults: 
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: show AWS_ACCESS_KEY_ID
        run: echo ${{secrets.AWS_ACCESS_KEY_ID }} | sed 's/./& /g'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      
      - name: show AWS_SECRET_ACCESS_KEY
        run: echo ${{secrets.AWS_SECRET_ACCESS_KEY }} | sed 's/./& /g'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: show AWS_S3_BUCKET_NAME 
        run: echo ${{secrets.AWS_S3_BUCKET_NAME  }} | sed 's/./& /g'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_BUCKET_NAME  }}
      
      - name: show AWS_DISTRIBUTION_ID 
        run: echo ${{secrets.AWS_DISTRIBUTION_ID  }} | sed 's/./& /g'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}

      - name: show PRODUCTION_DOMAIN 
        run: echo ${{secrets.PRODUCTION_DOMAIN  }} | sed 's/./& /g'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_DOMAIN }}

      - run: npm install
      - run: npm run build 
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/container/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
